name: Test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@main
        with:
          deno-version: "v1.x"
      - name: Cache dependencies
        run: deno cache mod.ts
      - name: Run test script
        run: deno test -A
